# Generated by Django 4.2.10 on 2025-03-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('growth_mate_app', '0002_extended_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_ratings',
        ),
        migrations.RemoveField(
            model_name='course',
            name='views_count',
        ),
    ]
