# Generated by Django 4.2.10 on 2025-03-30 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('growth_mate_app', '0003_course_enrolled_students_alter_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='growth_mate_app.course'),
        ),
    ]
