# Generated by Django 4.2.10 on 2025-03-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth_mate_app', '0007_alter_lesson_options_remove_lesson_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentblock',
            options={'ordering': ['order'], 'verbose_name': 'Content Block', 'verbose_name_plural': 'Content Blocks'},
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_content/%Y/%m/%d/'),
        ),
    ]
