# Generated by Django 5.1.7 on 2025-03-20 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth_mate_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='static/assets/images/communication.png', upload_to='static/course_images/')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
                ('about_this_course', models.TextField()),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='growth_mate_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('videos', models.FileField(blank=True, null=True, upload_to='static/course_media/videos/')),
                ('images', models.ImageField(blank=True, null=True, upload_to='static/course_media/images/')),
                ('course_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='growth_mate_app.coursecontent')),
            ],
        ),
    ]
