# Generated by Django 5.1.7 on 2025-03-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth_mate_app', '0002_course_coursecontent_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='static/assets/images/default_course.png', upload_to='static/course_images/'),
        ),
    ]
