# Generated by Django 5.1.7 on 2025-03-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth_mate_app', '0003_coursecontent_description_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static/course_content/images/'),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='static/course_content/videos/'),
        ),
    ]
